train:
    run: True
    n_class: 10
    dataset: 'mnist'
    p_list: [1,2,3,4]
    repeat: 5
    epsilon_list: [0, 0.2, 15]
    epsilon_list_short: [0, 0.1, 3]

train_opt:
    batch_size: 1000
    max_epoch: 51
    lr: 0.001

train_net:
    hidden_width: 500
    bias: True

plot:
    run: True